### ISSUE TITLE
Exclude option ignored when directly calling dir/file

### ISSUE THREAD

**Issue by jhossbach** [charliermarsh/ruff#1339]
MWE:
```toml
[tool.ruff]
exclude = [ "blah" ]
```
`blah/test.py`:
```python
import os
```
Running ruff on `.` returns nothing, but running `ruff ./blah` or `ruff ./blah/test.py` will return the diagnostics (F401) even if blah was excluded. Is this intentional?
