### ISSUE TITLE
pre-commit doesn't seem to pickup pyproject.toml setting for line-length

### ISSUE THREAD

**Issue by carlthome** [charliermarsh/ruff#1462]
I have a `pyproject.toml` with

```
[tool.black]
line-length = 100

[too.ruff]
line-length = 100
```
and a `.pre-commit-config.yaml` with
```
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.200
    hooks:
      - id: ruff
```

Yet when running `pre-commit run --all` I'm getting

```
E501 Line too long (89 > 88 characters)
```
from `ruff`.

Have I set something up wrong or is this intended behavior?
