### ISSUE TITLE
Latest release error

### ISSUE THREAD

**Issue by ofek** [charliermarsh/ruff#1464]
https://github.com/pypa/hatch/actions/runs/3804943026/jobs/6472530377

```
error missing field `banned-api` for key `tool.ruff.flake8-tidy-imports` at line 182 column 1
```

**Comment by ofek** [comment]
Config:

```toml
[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
```
