### ISSUE TITLE
pydocstyle plugin should implement match and match_dir options

### ISSUE THREAD

**Issue by marscher** [charliermarsh/ruff#1555]
Sometimes it's useful to exclude some files and or directories from this plugin, e.g. you want to allow tests to match the rigid docstyle conventions.
Since I want other linting plugins to be run on the pydocstyle excluded files, Ruffs global exclude does not seem to be the solution.

```toml
[ruff.tool.pydocstyle]
# convention numpy is currently equivalent to ignoring 'D107', 'D203', 'D212', 'D213', 'D402', 'D413'
convention = "numpy"
match = "(?!__)(?!_version)(?!conftest).*\\.py"
match_dir = "^(?!(tests|tags|asdf)).*"
```
