### ISSUE TITLE
fix failed to converge within 100 iterations, ruff-0.0.206

### ISSUE THREAD

**Issue by marscher** [charliermarsh/ruff#1575]
command: `ruff --fix $file  # code posted below`

output:
```
weldx/transformations/rotation.py:22:5: D203 1 blank line required before class docstring
weldx/transformations/rotation.py:22:5: D213 Multi-line docstring summary should start at the second line
weldx/transformations/rotation.py:29:9: D213 Multi-line docstring summary should start at the second line
weldx/transformations/rotation.py:39:9: D213 Multi-line docstring summary should start at the second line
weldx/transformations/rotation.py:49:9: D213 Multi-line docstring summary should start at the second line
weldx/transformations/rotation.py:65:9: D213 Multi-line docstring summary should start at the second line
Found 106 error(s) (100 fixed, 6 remaining).

```

pyproject.toml (ruff.tool section):

```toml
[tool.ruff]
exclude = [
    '__init__.py',
    'doc/conf.py',
]
# TODO: should be the following list, but Ruff does not yet impl all of them.
#    W503,W504
#    E203
#    C408
ignore = ['C408','E402']
line-length = 88
select = [
    'B',
    'C',
    'D',
    'E',
    'F',
    'W',
    'UP', # pyupgrade
    'T',  # flake8-print
    #'B950'  # not yet implemented by Ruff.
]

external = ["B950"]
pydocstyle = {convention = "numpy"}
pyupgrade = {keep-runtime-typing = true}
mccabe = {max-complexity = 15}
target-version = "py38"
per-file-ignores = {"**/{tests,tags,asdf}/**" = ["D"]}
```

code:
``` python
"""Contains tools to handle rotations."""
from __future__ import annotations

from typing import TYPE_CHECKING, Union

import pint
from scipy.spatial.transform import Rotation as _Rotation

from weldx.constants import U_
from weldx.constants import WELDX_UNIT_REGISTRY as UREG

if TYPE_CHECKING:  # pragma: no cover
    import numpy.typing as npt

_DEFAULT_LEN_UNIT = UREG.millimeters
_DEFAULT_ANG_UNIT = UREG.rad

ROT_META = "wx_rot"


class WXRotation(_Rotation):
    """Wrapper for creating meta-tagged `~scipy.spatial.transform.Rotation` objects.

    See `scipy.spatial.transform.Rotation` docs for details.
    """

    @classmethod
    def from_quat(cls, quat: npt.ArrayLike) -> "WXRotation":  # noqa
        """Initialize from quaternions.

        See `scipy.spatial.transform.Rotation.from_quat` docs for details.
        """
        rot = super().from_quat(quat)
        setattr(rot, ROT_META, {"constructor": "from_quat"})
        return rot

    @classmethod
    def from_matrix(cls, matrix: npt.ArrayLike) -> "WXRotation":  # noqa
        """Initialize from matrix.

        See `scipy.spatial.transform.Rotation.from_matrix` docs for details.
        """
        rot = super().from_matrix(matrix)
        setattr(rot, ROT_META, {"constructor": "from_matrix"})
        return rot

    @classmethod
    def from_rotvec(cls, rotvec: npt.ArrayLike) -> "WXRotation":  # noqa
        """Initialize from rotation vector.

        See `scipy.spatial.transform.Rotation.from_rotvec` docs for details.
        """
        rot = super().from_rotvec(rotvec)
        setattr(rot, ROT_META, {"constructor": "from_rotvec"})
        return rot

    @classmethod
    @UREG.check(None, None, "[]", None)
    def from_euler(
        cls,
        seq: str,
        angles: Union[pint.Quantity, npt.ArrayLike],
        degrees: bool = False,
    ) -> "WXRotation":  # noqa
        """Initialize from euler angles.

        See `scipy.spatial.transform.Rotation.from_euler` docs for details.
        """
        if isinstance(angles, pint.Quantity):
            if angles.u == U_(""):
                angles = angles.to("rad")
            degrees = "rad" not in str(angles.u)
            if degrees:
                angles = angles.to("degree")
            else:
                angles = angles.to("rad")
            angles = angles.m

        rot = super().from_euler(seq=seq, angles=angles, degrees=degrees)
        setattr(
            rot,
            ROT_META,
            {"constructor": "from_euler", "seq": seq, "degrees": degrees},
        )
        return rot
```

**Comment by charliermarsh** [comment]
Taking a look.

**Comment by charliermarsh** [comment]
I think the issue is that both `D203` and `D211` are enabled. I should add a warning for this. Those checks are incompatible (they exist to support different docstring conventions), so Ruff will just go back and forth fixing them endlessly.

I'd recommend disabling `D203`. In the next release, you could also remove `D` from your list and set:

```toml
[tool.ruff.pydocstyle]
convention = "google"  # Accepts: "google", "numpy", or "pep257".
```
