### ISSUE TITLE
banned-api not banning module import

### ISSUE THREAD

**Issue by sbdchd** [charliermarsh/ruff#1614]
with the config:

```toml
[tool.ruff.flake8-tidy-imports]
# Disallow all relative imports.
ban-relative-imports = "all"
[tool.ruff.flake8-tidy-imports.banned-api]
"httpx".msg = "Use kodiak.http"
```

the following code isn't banned

```python
from httpx import (
    AsyncClient,
    HTTPError,
    HTTPStatusError,
    Request,
    Response,
)
from httpx._config import DEFAULT_TIMEOUT_CONFIG
from httpx._types import TimeoutTypes
```

rel: https://github.com/charliermarsh/ruff/issues/1422#issuecomment-1370397812
