### ISSUE TITLE
Feature Request: Please support isort add_imports option

### ISSUE THREAD

**Issue by nefrob** [charliermarsh/ruff#1700]
With `isort` you can auto import things, i.e. in the `pyproject.toml`:

```toml
[tool.isort]
add_imports = "from __future__ import annotations"
```

This is a feature request for the same functionality in `ruff`

```toml
[tool.ruff.isort]
add_imports = "from __future__ import annotations"
