### ISSUE TITLE
error unknown variant `W503`

### ISSUE THREAD

**Issue by 12rambau** [charliermarsh/ruff#1746]
I am moving from `flake8` to `ruff` and one of my ignore statements is not recognized by 0.0.215. 

```toml
[tool.pytest.ini_options]
testpaths = "tests"

[tool.ruff]
fix = true
select = ["E", "F", "W", "I", "D", "N", "RUF"]
ignore = [
    "E501",  # line too long | Black take care of it
    "W605",  # invalid escape sequence | we escape specific characters for sphinx
    "W503",  # line break before binary operator | Black takes care of it
]

# init file are here to hide the internal structure to the user of the lib
exclude = ["*/__init__.py", "docs/source/conf.py"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
```

I checked and W503 do exist: https://www.flake8rules.com/rules/W503.html

Is it normal ? is it missing ? can I safely remove this ignore statement if it's not taken into account ?
