### ISSUE TITLE
Isort and Ruff Isort implementation incompatibilities

### ISSUE THREAD

**Issue by dbritto-dev** [charliermarsh/ruff#1876]
**test_linting.py**

```python
import json
import datetime as dt

_ = json.dumps({})
__ = dt.datetime.now()
```
**pyproject.toml** 

```toml
[project]
version = "1.0.0"
description = "<some-description>"
name = "<some-name>"
requires-python = ">=3.8"
dependencies = [
  "fastapi", "python-dotenv", "beanie", "auth0-python", "auth0-jwt-validator",
  "hypercorn", "slack-sdk"
]

[project.optional-dependencies]
dev = [
  "nox", "ruff", "black", "pytest", "pytest-cov", "safety", "bandit", "debugpy"
]
lint = ["ruff", "black"]
test = ["nox", "pytest", "pytest-cov"]
security-test = ["safety", "bandit"]

[tool.setuptools.packages]
find = {}

[tool.ruff]
line-length = 99
target-version = "py310"
select = ["B", "C", "E", "F", "W"]
ignore = ["E501", "B904", "B008"]
exclude = [
  "build", "configs", "*.egg-info", ".github", ".githooks", ".vscode", ".nox"
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
line-length = 99
target-version = ['py310']
preview = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["app"]
```
**Result**

![image](https://user-images.githubusercontent.com/1697714/212499482-2903dcfd-d6cb-4aba-b4df-be601eb3b636.png)

**Info**

![image](https://user-images.githubusercontent.com/1697714/212499536-97aee9f3-0c44-4df8-bf85-aa487320b33d.png)

**Note:**

Since ruff wasn't able to find any issue with the imports, it wasn't able to fix the sort imports

**Comment by charliermarsh** [comment]
You need to add `"I"` to your `select`, to enable import sorting -- like:

```toml
[tool.ruff]
line-length = 99
target-version = "py310"
select = ["B", "C", "E", "F", "W", "I"]
ignore = ["E501", "B904", "B008"]
exclude = [
  "build", "configs", "*.egg-info", ".github", ".githooks", ".vscode", ".nox"
]
```
