### ISSUE TITLE
pre-commit instructions not in sync with `ruff-pre-commit` repo

### ISSUE THREAD

**Issue by goretkin** [charliermarsh/ruff#2134]
https://github.com/charliermarsh/ruff/blob/605416922d193d2261bc8b5ed0de8741691a018d/README.md#usage has

```
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.233'
  hooks:
    - id: ruff
```

but the latest tag is https://github.com/charliermarsh/ruff-pre-commit/tree/v0.0.231 (there is no v0.0.233)
