### ISSUE TITLE
Implement isort `add_imports` option

### ISSUE THREAD

**Issue by ngnpope** [charliermarsh/ruff#2249]
It would be handy if we could have isort's [`add_imports`](https://pycqa.github.io/isort/docs/configuration/options.html#add-imports) configuration option.

This is quite often used to add `from __future__ import annotations`:

```toml
[tool.ruff.isort]
add_imports = ["from __future__ import annotations"]
```

It's probably relatively straightforward to also implement [`remove_imports`](https://pycqa.github.io/isort/docs/configuration/options.html#remove-imports) at the same time.

There are also `--add-import` and `--remove-import` command line options, but not sure how widely used they are.
