### ISSUE TITLE
Using global config is impacting the behaviour of the tests

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#2304]
When running the tests with this as global config.
```toml
# /home/jonathan/.config/ruff/ruff.toml
# https://github.com/charliermarsh/ruff#reference
target-version = "py37"
select = ["ALL"]
ignore = [
    "ANN101", # missing-type-self
    "ANN102", # missing-type-cls
    "ANN401", # dynamically-typed-expression
    "D10",    # missing-docstring
    "DTZ003", # call-datetime-utcnow
    "E501",   # line-too-long
]
unfixable = [
    "ERA001", # commented-out-code
    "F401",   # unused-import
    "F841",   # unused-variable
    "T20",    # print-found
]

[flake8-bugbear] # https://github.com/charliermarsh/ruff#flake8-bugbear
extend-immutable-calls = ["fastapi.Body", "fastapi.Depends"]

[flake8-builtins] # https://github.com/charliermarsh/ruff#flake8-builtins
builtins-ignorelist = []

[flake8-pytest-style] # https://github.com/charliermarsh/ruff#flake8-pytest-style-pt
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = "csv"

[isort]
known-third-party = []

[pep8-naming] # https://github.com/charliermarsh/ruff#pep8-naming
classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
    "sqlalchemy.orm.declared_attr",
]

[pydocstyle] # https://github.com/charliermarsh/ruff#pydocstyle
convention = "pep257"
```
Running `cargo test --all` fails with this error messages
```console
---- test_stdin_filename stdout ----
thread 'test_stdin_filename' panicked at 'assertion failed: `(left == right)`
  left: `"F401.py:1:1: INP001 File `F401.py` is part of an implicit namespace package. Add an `__init__.py`.\nF401.py:1:8: F401 `os` imported but unused\nFound 2 errors.\n1 potentially fixable with the --fix option.\n"`,
 right: `"F401.py:1:8: F401 `os` imported but unused\nFound 1 error.\n1 potentially fixable with the --fix option.\n"`', ruff_cli/tests/integration_test.rs:48:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_stdin_json stdout ----
thread 'test_stdin_json' panicked at 'assertion failed: `(left == right)`
  left: `"[\n  {\n    \"code\": \"INP001\",\n    \"message\": \"File `F401.py` is part of an implicit namespace package. Add an `__init__.py`.\",\n    \"fix\": null,\n    \"location\": {\n      \"row\": 1,\n      \"column\": 1\n    },\n    \"end_location\": {\n      \"row\": 1,\n      \"column\": 1\n    },\n    \"filename\": \"/home/jonathan/Documents/github/ruff/ruff_cli/F401.py\"\n  },\n  {\n    \"code\": \"F401\",\n    \"message\": \"`os` imported but unused\",\n    \"fix\": null,\n    \"location\": {\n      \"row\": 1,\n      \"column\": 8\n    },\n    \"end_location\": {\n      \"row\": 1,\n      \"column\": 10\n    },\n    \"filename\": \"/home/jonathan/Documents/github/ruff/ruff_cli/F401.py\"\n  }\n]\n"`,
 right: `"[\n  {\n    \"code\": \"F401\",\n    \"message\": \"`os` imported but unused\",\n    \"fix\": {\n      \"content\": \"\",\n      \"message\": \"Remove unused import: `os`\",\n      \"location\": {\n        \"row\": 1,\n        \"column\": 0\n      },\n      \"end_location\": {\n        \"row\": 2,\n        \"column\": 0\n      }\n    },\n    \"location\": {\n      \"row\": 1,\n      \"column\": 8\n    },\n    \"end_location\": {\n      \"row\": 1,\n      \"column\": 10\n    },\n    \"filename\": \"/home/jonathan/Documents/github/ruff/ruff_cli/F401.py\"\n  }\n]\n"`', ruff_cli/tests/integration_test.rs:70:5


failures:
    test_stdin_filename
    test_stdin_json

test result: FAILED. 7 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s

error: test failed, to rerun pass `-p ruff_cli --test integration_test`
```
