### ISSUE TITLE
Q000 different quotes in string

### ISSUE THREAD

**Issue by FieryDruid** [charliermarsh/ruff#2529]
ruff  `0.0.240`

I use single quotes for strings, settings from `.toml` file:
```toml
[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"
```
Case:
```python
test_1 = 'hello'
test_2 = "hello"
test_3 = "hello 'world'"
```
On this case `ruff` show error only for `test_2` string. I think it is because i use single quotes inside string in `test_3`
