### ISSUE TITLE
Error using '--force-exclude' with pre-commit

### ISSUE THREAD

**Issue by Ilya-Grigoriev** [charliermarsh/ruff#2555]
When I run pre-commit, this error comes out:
```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 2

error: the argument '--force-exclude' cannot be used multiple times

Usage: ruff.EXE check [OPTIONS] [FILES]...

For more information, try '--help'.
```
Using ruff with pre-commit.
```
rev: v0.0.240
    hooks:
      - id: ruff
        args:
          - --force-exclude
          - --extend-ignore=E501
```
`pyproject.toml`
```
[tool.ruff]
line-length = 80
```
