### ISSUE TITLE
Would be nice to have more support for isort options.

### ISSUE THREAD

**Issue by mikelane** [charliermarsh/ruff#2595]
In the imports, it's nice to have them all on separate lines. Using isort directly, I tend to use the following settings:

```toml
[tool.isort]
profile = "black"
multi_line_output = 3  # vertial hanging indent
force_grid_wrap = 2  # Force multiline when there are 2+ imports from the same module
```

This results in imports that look like this:

```python
from functools import cache
from itertools import (
    combinations,
    permutations,
)

from pydantic import (
    BaseModel,
    EmailStr,
)
```

And then if I add an import from itertools, I can see the changed import quickly in the PR because that change will have its own line. 

As far as I can tell, this setting isn't included in ruff. I'm loving what I'm seeing with ruff, so I'd love to have the option of setting the `multi_line_output` and `force_grid_wrap` options in ruff.
