### ISSUE TITLE
False positive F841: typing automatically removed as unused by ``--fix`` when they are not

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [charliermarsh/ruff#2603]
I'm using v0.241, on the following code:

```python
KeyTupleT = Tuple[Type[nodes.NodeNG], str]
keys_checked: set[KeyTupleT] = set()
```
The following conf:
```toml
[tool.ruff]
select = ["E", "F"]
fixable = ["A", "B", "C", "D", "E", "F"]
```
The output of ``ruff --fix`` is:
```python
Tuple[Type[nodes.NodeNG], str]
keys_checked: set[KeyTupleT] = set()
```
But ``KeyTupleT`` is used in the typing.

**Comment by charliermarsh** [comment]
Definitely looks like a bug -- will take a look!

**Comment by charliermarsh** [comment]
I'm unable to reproduce this. Is that the full code snippet and configuration? Are you able to repro with `--isolated` at all?

I wonder if you perhaps have a lower Python version set, and so we're not treating `set[X]` as a reference to `X`? Just a guess...

**Comment by Pierre-Sassoulas** [comment]
I just tried but I can't reproduce using only ruff either. The issue happen using ``pre-commit`` and the conf in our ``pyproject.toml``.
```yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.241"
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: *fixtures
```        
```toml
[tool.ruff]
select = ["E", "F", "B"]
ignore = [
    # "F841", # False positive for typing
    "B905", # Not enforced previously
]
fixable = ["A", "B", "C", "D", "E", "F"]
line-length = 125
```
 Strangely I do not manage to reproduce with the minimal example like I originally did... I don't know exactly why, I added some configuration for ``B`` message and ignore since. But I'm still reproducing the original bug in https://github.com/Pierre-Sassoulas/pylint/tree/add-ruff-to-pre-commit (If you remove ``"F841", # False positive for typing`` in ``pyproject.toml`` and launch ``pre-commit run ruff --all-files``), there's a modification in ``pylint/extensions/code_style.py`` for both python 3.10 and python 3.11.
