### ISSUE TITLE
`ignore-names` doesn't seem to work for me

### ISSUE THREAD

**Issue by tmke8** [charliermarsh/ruff#2612]
I have code similar to this:
```python
def f(C: float) -> None:
    print(f"cost parameter: {C}")
```
And I tried to exclude `C` from the naming check with
```toml
[tool.ruff.pep8-naming]
ignore-names = ["C"]
```
But I still get
```
naming_test.py:1:7: N803 Argument name `C` should be lowercase
Found 1 error.
```

I might be doing something wrong, but I can't figure out what.
