### ISSUE TITLE
`N815`: Regression of `classmethod-decorators` in v0.0.244

### ISSUE THREAD

**Issue by ngnpope** [charliermarsh/ruff#2673]
For this code:

```python
import pydantic

class Thing(pydantic.BaseModel):
    @pydantic.root_validator(pre=True)
    def _validate_something(cls, values):
        return values
```

And this configuration:

```toml
[pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.root_validator"]
```

I get this output:

```console
❯ pipx inject ruff ruff==0.0.243
  injected package ruff into venv ruff
done! ✨ 🌟 ✨

❯ ruff --version
ruff 0.0.243

❯ ruff --config bug.toml --select N805 bug.py 

❯ pipx inject ruff ruff==0.0.244
  injected package ruff into venv ruff
done! ✨ 🌟 ✨

❯ ruff --version
ruff 0.0.244

❯ ruff --config bug.toml --select N805 bug.py 
bug.py:5:29: N805 First argument of a method should be named `self`
Found 1 error.
```
