### ISSUE TITLE
`RUF100` strips valid `noqa` comments when file contains syntax error

### ISSUE THREAD

**Issue by stinodego** [charliermarsh/ruff#2853]
See the example below.

### Config

```toml
[tool.ruff]
fix = true
select = ["W", "RUF"]

[tool.ruff.pycodestyle]
max-doc-length = 88
```

### Code

```
class Repro:
    def foo(self) -> None:
        """Docstring way toooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo long."""  # noqa: W505
        ...

@cool_decorator()  # Syntax error due to indentation
    def bar(self) -> None:
        ...
```

Running `ruff .` results in the `noqa` comment erroneously being stripped.

### Version
Latest (`0.0.246`)
