### ISSUE TITLE
N805 False Positive

### ISSUE THREAD

**Issue by sharyar** [charliermarsh/ruff#2868]
Noticed that ruff gives a false positive with pydantic validation method as shown here:

```python
class MyClass(BaseModel):
    name: str

    @validator('name')
    def name_validator(cls, v):
        if v is None:
            return "John Smith"
        else:
            return v

```
Running `ruff . --fix` gives me the following message: `...N805 First argument of a method should be named "self"`
Ruff Version: ruff 0.0.246

Sections from pyproject.toml:
```
[tool.ruff]
fix = true
line-length = 120
target-version = "py39"
select = ["I", "E", "F", "Q", "W", "N"]
ignore = [
    "F541",
    "N803",
    "N806",
    "Q000",
    "Q003",
]
[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.flake8-quotes]
avoid-escape = false
inline-quotes = "double"
docstring-quotes = "double"
multiline-quotes = "double"

[tool.ruff.isort]
known-first-party = [
    "tools"
]
```

**Comment by g-as** [comment]
See https://github.com/charliermarsh/ruff#classmethod-decorators

**Comment by charliermarsh** [comment]
Yeah you should be able to add:

```toml
[tool.ruff.pep8-naming]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
classmethod-decorators = ["classmethod", "pydantic.validator"]
```

...to help with this. But if that doesn't work, let us know!

**Comment by sharyar** [comment]
Thank you! Will do :)

**Comment by charliermarsh** [comment]
Thanks for the clear issue.

**Comment by sharyar** [comment]
Hi @charliermarsh, it looks like this doesn't work unfortunately. I have to manually disable the N805 check to force the error to go away.

**Comment by sharyar** [comment]
Here is part of my config file: 
![image](https://user-images.githubusercontent.com/9103610/218803637-ada7ad5b-45a4-47db-93b2-32b2647d0349.png)

And here is the error still showing up: 
![image](https://user-images.githubusercontent.com/9103610/218803773-88955901-301a-4404-a942-353d73755b48.png)

**Comment by g-as** [comment]
```toml
[tool.ruff.pep8-naming]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
classmethod-decorators = ["classmethod", "validator"]
```
since you called the decorator with `@validator` (and not `@pydantic.validator`)

**Comment by sharyar** [comment]
That does not work either sadly. Just tried it.

**Comment by charliermarsh** [comment]
I just tested myself and this works as expected for me:

```py
from pydantic import validator

class MyClass(BaseModel):
    name: str

    @validator('name')
    def name_validator(cls, v):
        if v is None:
            return "John Smith"
        else:
            return v
```

Along with:

```toml
[tool.ruff.pep8-naming]
# Allow Pydantic's `@validator` decorator to trigger class method treatment.
classmethod-decorators = ["classmethod", "pydantic.validator"]
```

Gives me empty output with `ruff foo.py --select N` (and an error if I remove `"pydantic.validator"` from that list).

Can you post the entire file? Are you perhaps importing `validator` from some other file?

**Comment by sharyar** [comment]
I realized the issue. I was on an earlier version of ruff (my poetry.lock file cause me to go back a version). Sorry to bother you guys! Great job on the application! i heard about you on the python podcast and since then have been a convert :D Getting everyone to use it 👍

**Comment by charliermarsh** [comment]
Amazing, thank you for the kind words! (I think this was broken for a release or two due to an internal refactor, but should be fixed in the last few.)

**Comment by copdips** [comment]
> I just tested myself and this works as expected for me:
> 
> ```python
> from pydantic import validator
> 
> class MyClass(BaseModel):
>     name: str
> 
>     @validator('name')
>     def name_validator(cls, v):
>         if v is None:
>             return "John Smith"
>         else:
>             return v
> ```
> 
> Along with:
> 
> ```toml
> [tool.ruff.pep8-naming]
> # Allow Pydantic's `@validator` decorator to trigger class method treatment.
> classmethod-decorators = ["classmethod", "pydantic.validator"]
> ```
> 
> Gives me empty output with `ruff foo.py --select N` (and an error if I remove `"pydantic.validator"` from that list).
> 
> Can you post the entire file? Are you perhaps importing `validator` from some other file?

Thanks, and for me without classmethod is ok too.

```toml
[tool.ruff.pep8-naming]
classmethod-decorators = ["pydantic.validator"]
```

**Comment by blakeNaccarato** [comment]
I was bit by this old issue again when bumping a project to Pydantic v2 while still using the old interface (e.g. `from pydantic.v1 import ...`). It's simple enough to fix, but it took me a minute to figure out, so I figured I'd detail it here in case a search engine brings you here as well. You must add `pydantic.v1.validator` to your `classmethod-decorators`.

```TOML
[tool.ruff.pep8-naming]
classmethod-decorators = ["pydantic.validator", "pydantic.v1.validator"]
```
