### ISSUE TITLE
isort: bug in sorting sub-package modules

### ISSUE THREAD

**Issue by spaceone** [charliermarsh/ruff#3059]
`.isort.cfg`
```ini
[settings]
known_first_party=foo.bar,baz
known_third_party=foo,blub,blah
```

valid isort-compatible code:
```python
import sys

import blah
import blub
import foo
from foo import bar, baz

import baz
import foo.bar
from foo.bar import blah, blub
```

`pyproject.toml`:
```toml
[tool.ruff]
select = ["I"]
[tool.ruff.isort]
known-first-party = ["foo.bar", "baz"]
known-third-party = ["foo", "blub", "blah"]
```

```console
$ ruff --fix --diff foo.py
--- foo.py
+++ foo.py
@@ -3,8 +3,8 @@
 import blah
 import blub
 import foo
+import foo.bar
 from foo import bar, baz
+from foo.bar import blah, blub
 
 import baz
-import foo.bar
-from foo.bar import blah, blub

Would fix 1 error.
```
