### ISSUE TITLE
`isort` ordering of imports not being enforced.

### ISSUE THREAD

**Issue by brysontyrrell** [charliermarsh/ruff#3188]
I'm experimenting replacing `isort` with `ruff` but it doesn't seem to be enforcing the order of imports even if I explicitly set `order-by-type = true`.

Here's what is in `pyproject.toml`:

```toml
[tool.ruff]
line-length = 100
target-version = "py39"
src = [
    "src",
    "test"
]


[tool.ruff.isort]
known-first-party = [ "my-package" ]
order-by-type = true
force-sort-within-sections = true
```

Here's the test Python file `my-package/__init__.py`:
```python
from .shared import IMPORT_ME  # first-party

import json  # standard lib
import requests  # third party


print(requests)
print(json)
print(IMPORT_ME)
```

`isort` properly returns an error when it checks this file:
```
ERROR: /path/to/my-package/__init__.py Imports are incorrectly sorted and/or formatted
```

Ruff is at version `0.0.252`.
