### ISSUE TITLE
TCH (flake8-type-checking) not working as expected

### ISSUE THREAD

**Issue by roansong** [charliermarsh/ruff#3359]
# Overview

Running `ruff` is great overall, but the TCH checks don't appear to be behaving correctly for me.

```
ruff version: 0.0.254
```

## Code Snippet
I'm using poetry here, in a minimal project.

`test.py`
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable

def func(a: Callable) -> int:
    return 1
```

`pyproject.toml`
```toml
[tool.poetry]
name = "test-issue"
version = "0.1.0"
description = ""
authors = ["Roan Song <roansong@gmail.com>"]
readme = "README.md"
packages = [{include = "test_issue"}]

[tool.poetry.dependencies]
python = "^3.10"
ruff = "^0.0.254"
```

## Command

```bash
poetry run ruff check . --isolated --select TCH
test.py:4:33: TCH004 Move import `collections.abc.Callable` out of type-checking block. Import is used for more than type hinting.
Found 1 error.
```

I didn't manage to reproduce the following error consistently, but here's a screenshot of the opposite happening, where the VS Code plugin correctly says I should move code into a type checking block, but running `ruff check . --select TCH --isolated` showed no errors
<img width="964" alt="image" src="https://user-images.githubusercontent.com/14807642/223126969-4000029b-5c46-443a-8c1b-d6e8c5501190.png">
