### ISSUE TITLE
Keep `# noqa` comments when forcing single-line imports

### ISSUE THREAD

**Issue by stinodego** [charliermarsh/ruff#3418]
Consider the following file `repro.py`:

```python
from datetime import date, time  # noqa: F401
```

And let's say my ruff config has `isort` lints, with force-single-line option:

```toml
[tool.ruff]
fix = true
select = ["F", "I"]

[tool.ruff.isort]
force-single-line = true
```

Running `ruff repro.py` results in the `time` import being deleted:

```python
from datetime import date  # noqa: F401
```

Running `ruff repro.py --unfixable=F401` results in:

```python
from datetime import date  # noqa: F401
from datetime import time
```

So the problem here is that the `# noqa` comment is not reproduced on the extra lines. Desired outcome would be:

```python
from datetime import date  # noqa: F401
from datetime import time  # noqa: F401
```

This is on the latest version of ruff (`0.0.254`).
