### ISSUE TITLE
Warning from VS Code extension but not from CLI

### ISSUE THREAD

**Issue by adamhl8** [charliermarsh/ruff#3551]
I have some code that looks like this:

```python
def foobar():
    foo = "foo"
    if bar():
        foo = "bar"
    return foo
```

Which I'm correctly getting a `Unnecessary variable assignment before 'return statementRuff(RET504)'` warning in VS Code.

However, when I run ruff via CLI on this file I don't get any warnings.

`ruff -v my_module.py`:
```
[2023-03-15][17:24:14][ruff_cli::commands::run][DEBUG] Identified files to lint in: 1.764392ms
[2023-03-15][17:24:14][ruff_cli::commands::run][DEBUG] Checked 1 files in: 2.313242ms
```
My config:

```toml
[tool.ruff]
line-length = 120
target-version = "py310"
select = ["E", "F", "RET"]
```
