### ISSUE TITLE
Ruff breaking randomly on CI with pre-commit

### ISSUE THREAD

**Issue by mounirmesselmeni** [charliermarsh/ruff#3558]
Running ruff in CI is recently is sometime failing with this error:

```
/lib/ld-linux-aarch64.so.1: No such file or directory
```

Ruff version:

```yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.256"
    hooks:
      - id: ruff
```

Configuration

```toml
[tool.ruff]
# Docs: https://beta.ruff.rs/docs/
# Rules: https://beta.ruff.rs/docs/rules/
select = ["F", "E", "B", "C4", "EXE", "ISC", "ICN", "INP", "PIE", "SIM", "W", "T20", "UP", "T10", "G", "DJ001", "DJ008", "C90", "ERA"]
# Later on might be useful C/C90 (Compexity), ERA (Found commented-out code), FBT
ignore = ["B008", "SIM102"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["F", "E", "B", "C4", "EXE", "ISC", "ICN", "INP", "PIE", "SIM", "W", "T20", "UP"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".mypy_cache",
    ".pre-commit-cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "venv",
    "docs",
    "__pycache",
    "**/migrations/*",
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.per-file-ignores]
"**/management/commands/*.py" = ["T20"]
```

Issue happened on another project running python 3.11

I can't reproduce the issue locally, but maybe you have some idea about the cause.

If helping, I'm using Gitlab CI and caching of pre-commit files.

```
PRE_COMMIT_HOME: ".cache/.pre-commit-cache/"
```

```yaml
cache:
    key: $CI_PROJECT_NAME-precommit-cache-v1
    paths:
      - .cache/.pre-commit-cache/
```

If I clear the cache and re-run the job then it's fixed, maybe I'm missing something here to cache the file /lib/ld-linux-aarch64.so.1

**Comment by mounirmesselmeni** [comment]
Good point, nothing special as I'm using the shared gitlab runners, so no tags or target is set in the job.

```yaml
python-precommit:
  extends: .base-job
  image:
    name: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    entrypoint: [""]
  stage: test
  variables:
    PRE_COMMIT_HOME: ".cache/.pre-commit-cache/"
  script:
    # fix git dubious ownership caused by gitlab runner helper fetching the repo as root
    # while we run as non-root with app user
    - git config --global --add safe.directory $CI_PROJECT_DIR
    # Make sure all pre-commit checks are passing
    - pre-commit run --all
  rules:
    - exists:
        - ".pre-commit-config.yaml"
  interruptible: true
  cache:
    key: $CI_PROJECT_NAME-precommit-cache-v1
    paths:
      - .cache/.pre-commit-cache/
```
