### ISSUE TITLE
isort: bad interaction between `force-sort-within-sections` and `force-to-top`

### ISSUE THREAD

**Issue by bluetech** [charliermarsh/ruff#3630]
Given this config:

```toml
[tool.isort]
force_to_top = ["typing"]
force_sort_within_sections = true

[tool.ruff]
select = ["I001"]
[tool.ruff.isort]
force-to-top = ["typing"]
force-sort-within-sections = true
```

and this isort-clean file:

```py
from typing import Any
import abc
from abc import ABCMeta
import os
```

ruff fix gives:

```py
import abc
import os
from typing import Any
from abc import ABCMeta
```

It looks like `force-sort-within-sections` (which says to not sort the `import`s and `from`s separately) is ignored. But if I comment out the `force-to-top = ["typing"]` setting, ruff gives:

```py
import abc
from abc import ABCMeta
import os
from typing import Any
```

which is correct. So I'm guessing the two settings together cause the issue.

(I'll try to fix this issue when I get a chance, unless someone beats me to it)

Version: ruff 0.0.257
