### ISSUE TITLE
Disable options specifically for .pyi files

### ISSUE THREAD

**Issue by PedroPerpetua** [charliermarsh/ruff#3649]
Currently I'm having an issue in my project where I have a `./typing` folder that contains only stubs (`.pyi` files) alongside my project folders, in a structure similar to this:
```
src/
├── ...
├── ...
└── ...
typing/
└── module/
    └── file.pyi
pyproject.toml
```

I'm facing an issue specifically with a clash of _ruff's isort_ options and _black_; By setting `lines-after-imports = 2` under _ruff_, _black_ and _ruff_ will clash on the `.pyi` files, where _ruff_ will apply 2 lines between the imports and stubs, and _black_ will apply 1 line, conforming to the relevant PEP. This does not happen to the normal python files under `src`, where both tools leave 2 blank lines between the imports and code.

Is there a way to configure _ruff_ to also leave only one line in the `.pyi` files? If not, I think it would be useful to be able to configure for these files specifically, the same way you can set configurations specifically for `__init__.py` files.

Relevant configurations I use:
```toml
# pyproject.toml
[tool.ruff]
src = ["src", "typing"]
fix = true
select = ["F", "I", "W", "E"]

[tool.ruff.isort]
lines-after-imports = 2
no-lines-before = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
```

Currently, my fix is to have a second `pyproject.toml` file under `./typing` with the following contents:
```toml
[tool.ruff]
extend = "../pyproject.toml"

[tool.ruff.isort]
# Stub files have a different default lines between imports
lines-after-imports = -1
no-lines-before = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
```

Extra information:
- Ruff version: `0.0.257`
