### ISSUE TITLE
Providing the line length, max-complexity, etc in --statistics

### ISSUE THREAD

**Issue by cclauss** [charliermarsh/ruff#3755]
@JonathanPlasse

Similar to #3748 but for providing the value for `line-length`, `max-complexity`, `max-args`… when running `ruff --select=ALL --statistics .`

When linting a new repo, I might need to set all seven of the following numbers.
```toml
[tool.ruff]
line-length = 100  # Recommended: 88

[tool.ruff.mccabe]
max-complexity = 15   # Recommended: 10

[tool.ruff.pylint]
max-args = 8   # Recommended: 5
max-branches = 17   # Recommended: 12
max-returns = 12   # Recommended: 6
max-statements = 52   # Recommended: 5p
```
It takes a bit of trial and error to find the length of longest line or the most complex function.  It would save a lot of time and aggravation if `--statistics` did not just show a random `E501` error but instead showed me the error message from the longest line.  I could the copy that value and paste it into `pyproject.toml`
