### ISSUE TITLE
`required-imports  = ["from __future__ import annotations"]` reports missing import in `pyi` files

### ISSUE THREAD

**Issue by bryanforbes** [charliermarsh/ruff#3928]
Ruff version: 0.0.261

Given the following configuration:

```toml
[tool.ruff]
select = ["I"]

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]
```

And the following file at `stubs/my_thing/__init__.pyi`:

```python
def do_something() -> None: ...
```

`ruff` reports that `from __future__ import annotations` is missing from `stubs/my_thing/__init__.pyi`. This is contrary to how `isort` works: `isort` does not enforce this import for `pyi` files because stub files ["are treated as if `from __future__ import annotations` is enabled"](https://typing.readthedocs.io/en/latest/source/stubs.html#syntax).

**Comment by bryanforbes** [comment]
@charliermarsh it might also be a good idea to implement `Y044` from `flake8-pyi` to complement this change

**Comment by charliermarsh** [comment]
I'll fix this tonight.

**Comment by Avasam** [comment]
Related: https://github.com/charliermarsh/ruff/issues/3072#issuecomment-1500721160

My current config:
```toml
[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.per-file-ignores]
"*.pyi" = [
  "I002", # from __future__ import annotations
]
```
