### ISSUE TITLE
Improve `PGH003` to require codes for `# pyright: ignore`

### ISSUE THREAD

**Issue by bryanforbes** [charliermarsh/ruff#3935]
Ruff version: 0.0.261

Given the following configuration:

```toml
[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff]
select = ["PGH003"]
```

And the following file `test.py`:

```python
from __future__ import annotations


class One:
    def do_something(self, a: int) -> None:
        ...


class Two(One):
    def do_something(self, a: str) -> None:  # pyright: ignore
        ...
```

No error is generated for line 10. It would be nice if `PGH003` checked for `# pyright: ignore` without codes.
