### ISSUE TITLE
Support for isort's custom sections and ordering

### ISSUE THREAD

**Issue by robhudson** [charliermarsh/ruff#4061]
Support for [custom sections and ordering](https://pycqa.github.io/isort/docs/configuration/custom_sections_and_ordering.html)

I'd like to use `ruff` to replace `isort` in my project, but currently this is the blocking feature. The project is a Django project and we like to group our Django imports separately from the other 3rd party imports, which `isort` supports via the above.

If this is already possible with `ruff`, it was unclear to me reading the docs and options available. Thanks.

**Comment by g-as** [comment]
This was shipped in the latest release:

https://github.com/charliermarsh/ruff/releases/tag/v0.0.262

**Comment by g-as** [comment]
```TOML

[tool.ruff.isort]
known-first-party = ["valor", "config"]
extra-standard-library = ["_csv", "_typeshed", "typing_extensions"]
section-order = ["future", "standard-library", "django", "django-contrib", "third-party", "first-party", "tests-deps", "tests", "local-folder"]

[tool.ruff.isort.sections]
django = ["django"]
django-contrib = ["django.contrib"]
tests-deps = ["django.test", "factory", "faker", "pytest", "pytest_django", "respx", "testfixtures", "time_machine", "unittest"]
tests = ["tests"]
```
