### ISSUE TITLE
Docs request: `autoflake` in Rules page

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4107]
https://beta.ruff.rs/docs/rules/ mentions that `ruff` reimplements `autoflake`.

However, in the Rules sidebar (where relevant codes are listed), `autoflake` is not mentioned.

Can we document what codes pertain to `autoflake`?

**Comment by charliermarsh** [comment]
Hmm, it doesn't quite fit into our documentation paradigm, because `autoflake` is just a tool that adds autofix behavior for a small subset of the Pyflakes violations -- it doesn't define any violations of its own. I'm not sure that it's important that users know which rules that includes. What's the use motivation? Is this answer here sufficient? :)

**Comment by charliermarsh** [comment]
Closing but let me know if you have any follow-up questions.

**Comment by jamesbraza** [comment]
I am trying to migrate much of my full `pre-commit` config to `ruff`, one of them is `autoflake`.  I see it's mentioned in the `README` as being replace-able, but I am not sure:
- What codes are relevant
- Any configuration necessary

I run `autoflake` like so:

```yaml
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --remove-rhs-for-unused-variables
          - --remove-unused-variables
          - --exclude=somelocaldir
```

I made this docs request mainly because an `autoflake-to-ruff` (inspired by [`flake8-to-ruff`](https://pypi.org/project/flake8-to-ruff/)) conversion is not clear to me
