### ISSUE TITLE
Docs bug: default `show-fixes`

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4113]
From https://beta.ruff.rs/docs/settings/#show-fixes

```toml
[tool.ruff]
# By default, always enumerate fixed violations.
show-fixes = true
```

Specifically the comment:

> `# By default, always enumerate fixed violations.`

This comment is incorrect, the default of `show-fixes` is actually `false`.  The comment should say something like:

> `# Enumerate all autofixed violations.`
