### ISSUE TITLE
force-exclude doesn't work in subdirectory

### ISSUE THREAD

**Issue by brandonchinn178** [charliermarsh/ruff#4127]
When a python project is in a subdirectory (e.g. the `pyproject.toml` is in `subdir/pyproject.toml`), `force-exclude` no longer excludes files passed on the command line.

This is an issue when using ruff in a pre-commit hook. I could have the pre-commit hook cd into the subdirectory, but then I'd need to strip the prefix on all arguments

## Repro

Create the following files:
```toml
# subdir/pyproject.toml
[tool.ruff]
select = ["F"]
extend-exclude = ["skip.py"]
force-exclude = true
```
```py
# subdir/skip.py
import math
```
```py
# subdir/foo.py
import math
```

1. `python3 -m venv venv`
2. `venv/bin/pip install ruff`
3. `venv/bin/ruff subdir/`
    * ✅  Finds `subdir/foo.py`
4. `venv/bin/ruff subdir/*.py`
    * 💥  Finds `subdir/foo.py` and `subdir/skip.py`
5. `(cd subdir && ../venv/bin/ruff *.py)`
    * ✅  Finds `subdir/foo.py`
