### ISSUE TITLE
[Autofix error] SIM105 Use `contextlib.suppress(KeyError)` instead of `try`-`except`-`pass`

### ISSUE THREAD

**Issue by bittner** [charliermarsh/ruff#4241]
**Code Snippet:**

```python
class EnvironContext(patch.dict):
    ...

    def __enter__(self):

        super(EnvironContext, self).__enter__()

        for key in self.clear_variables:
            try:
                self.in_dict.pop(key)
            except KeyError:
                pass
```

**Executed command:**

```console
ruff . --fix
```

**Error tried to fix:**

```python
cli_test_helpers/decorators.py:58:13: SIM105 Use `contextlib.suppress(KeyError)` instead of `try`-`except`-`pass`
```

**Relevant settings:**

```toml
[tool.ruff]
extend-exclude = ["examples"]
extend-select = ["B", "BLE", "C4", "C90", "COM", "DJ", "DTZ", "EM", "G", "I", "N", "PIE", "PL", "PT", "PTH", "R", "S", "SIM", "T10", "TID", "W", "YTT"]

[tool.ruff.per-file-ignores]
"cli_test_helpers/commands.py" = ["S602"]
"setup.py" = ["PTH"]
"tests/*.py" = ["S101"]
```

**Ruff version:** 0.0.264

## Full Source Code and Additional Details

- See https://github.com/painless-software/python-cli-test-helpers/pull/39
