### ISSUE TITLE
Implement `--extend-fixable` and `--extend-unfixable` variants in CLI

### ISSUE THREAD

**Issue by ljnsn** [charliermarsh/ruff#4289]
Consider the following ruff config:

```toml
[tool.ruff]
fix = true
unfixable = ["F401", "F841"]
```

F401 and F841 are added as unfixable so that ruff doesn't automatically remove violating lines on file save (it's set up in the editor for autoformat). I do want to enable them in my pre-commit config though. So what I have done is configure the ruff hook like so:

```yaml
      - id: ruff
        name: ruff
        entry: ruff
        args: ["--fixable=F401,F841"]
        require_serial: true
        language: system
        types: [python]
```

However, this makes ruff consider **only** those two codes as fixable. So I thought I could fix it by passing --unfixable=E501, for example, assuming that would override the value set in the ruff config. The doesn't seem to be the case though, ruff still does not fix the errors.

This does not depend on pre-commit btw, the same can be reproduced by just running ruff from CLI. Essentially, I'm looking for a way to overwrite unfixable, without using --isolated, because there is more config than the minimal example above.

Is there a generally recommended way to do this?
