### ISSUE TITLE
Add config to disable S101 (assert detected) and a few others in test folders

### ISSUE THREAD

**Issue by jankatins** [charliermarsh/ruff#4368]
Per convention, testfolders usually reside in `<reporoot>/test/` or `<reporoot>/tests/`. Right now, every time I add certain rules, specifically S101, ARG, FBT, and a few others (e.g. via "ALL"), I have to add a folder exclude for these rules for the `tests/` folder:

```toml

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
]
```

 It would be really nice if ruff would do that automatically, E.g. by disabling the above rules via a central `test-files` list which is on a commonly used default:

```toml
[tool.ruff]
# To disable tests which are ok in tests -> would not need to be set as it would be a nice default
test-files =  ["tests/**/*.py", "test/**/*.py"]
```

This was already discussed in https://github.com/charliermarsh/ruff/issues/714 where the original reporter (@harupy) closed the issue after confirming the per folder overwrites.
