### ISSUE TITLE
Support for isorts add import functionality

### ISSUE THREAD

**Issue by gaborbernat** [charliermarsh/ruff#4462]
https://pycqa.github.io/isort/docs/configuration/options.html#add-imports
example use case to add the import annotations:

```toml
[tool.isort]
known_first_party = ["helpers", "package_info"]
profile = "black"
add_imports = ["from __future__ import annotations"]
```
