### ISSUE TITLE
Intellij quick-fix for un-sorted imports not working

### ISSUE THREAD

**Issue by HansAarneLiblik** [charliermarsh/ruff#4596]
I'm seeing an issue with ruff and quick-fixes it offers to Intellij

I have the following file
```py
from typing import assert_type, assert_never


if __name__ == '__main__':
    assert_never("test")
    assert_type(123, int)
```

and `ruff` complains about imports

![image](https://github.com/charliermarsh/ruff/assets/5418540/1b26ab2a-1790-49a7-8d18-be990b521765)

When I click `organize imports`, it breaks the code

```py
ffrom typing import assert_never, assert_type

f __name__ == '__main__':
    assert_never("test")
    assert_type(123, int)
```

Executing the fix from command line works `ruff . --fix`

My config from `pyproject.toml`
```toml
[tool.isort]
profile = "black"
line_length = 120
filter_files = true


[tool.ruff]
line-length = 120
target-version = "py310"
select = [
  "E",    # pycodestyle
  "W",    # pycodestyle
  "F",    # pyflakes
  "I",    # isort
  "C4",   # flake8-comprehensions
  "TID",  # flake8-tidy-imports
]
```

Ruff version is `0.0.269` and I'm using the Ruff plugin for IntelliJ IDEs
