### ISSUE TITLE
Isort I001 conflicts with pylint C0411

### ISSUE THREAD

**Issue by sansmoraxz** [charliermarsh/ruff#4672]
Take the following code block as an example:

```py
import numpy as np
from lamdacust.handler import lambda_handler
from moto import mock_s3, mock_sqs
```

Here `lamdacust` is the user defined module

The above order is valid according to ruff's rule I001, but not according to pylint C0411 which says to follow the order of standard imports first, then third-party libraries, then local imports.

Ruff version: 0.0.269
Editor: VSCode

**Comment by charliermarsh** [comment]
I'm guessing that Ruff isn't picking up lambdacust as first-party. Can you share your directory structure and configuration file? E.g., are you using a `src` directory or something like that?

**Comment by sansmoraxz** [comment]
No not using src

Here's the structure
```
.
├── lamdacust
│   ├── handler.py
│   ├── __init__.py
│   └── loaders.py
├── poetry.lock
├── pyproject.toml
├── README.md
└── tests
    ├── data
    │   └── text.txt
    ├── __init__.py
    ├── pyproject.toml
    └── test_handler.py
```

**Comment by sansmoraxz** [comment]
The config I addopted from somewhere not sure where from

```toml
[tool.poetry]
name = "lamdacust"
version = "0.1.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.3"
pillow = "^9.5.0"

[tool.poetry.group.dev.dependencies]
boto3 = "^1.26.135"
botocore = "^1.29.135"
jupyter = "^1.0.0"
boto3-stubs = {version = "^1.26.135", extras = ["s3", "sqs"]}
moto = {extras = ["s3"], version = "^4.1.9"}
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
ruff = "*"
ruff-lsp = "*"
pylint = "^2.17.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
skip-string-normalization = 1

[tool.ruff]
# https://beta.ruff.rs/docs/rules/
select = ["ALL"]

[tool.black]
skip-string-normalization = 1

[tool.ruff]
# https://beta.ruff.rs/docs/rules/
select = ["ALL"]


ignore = ["INP001", # implicit-namespace-package
          "ANN",    # type annotations
          "T20",    # flake8-print (warns when there are print statements)
          "ARG001", # unused-argument

          "D212", # See https://github.com/charliermarsh/ruff/issues/2281

          "D211", # See https://github.com/charliermarsh/ruff/issues/2281
]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Same as black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

# Enumerate all fixed violations.
show-fixes = true
# Show source code for each violation.
show-source = true

# This is how you tell Q000 errors to prefer single quotes
[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.pydocstyle]
convention = "numpy"  # Or "numpy", or "pep257" or "google"

```
