### ISSUE TITLE
TID rule with namespace packages

### ISSUE THREAD

**Issue by Saelyos** [charliermarsh/ruff#4758]
I wanted to replace `absolufy-imports` with ruff `TID` rule, but it doesn't seems to handle namespaces correctly:

### A minimal code snippet that reproduces the bug
Structure
```
mynamespace/
    mypackage/
        __init__.py
        foo.py
        bar.py
pyproject.toml
```
foo.py
```python
from .bar import Bar
b = Bar()
```
bar.py
```python
class Bar:
    pass
```
###  The command you invoked
ruff ./mynamespace/mypackage/foo.py --fix

###  Expected fix 
```python
from mynamespace.mypackage.bar import Bar 
```

###  Actual fix
```python
from mypackage.bar import Bar 
```

###  The current Ruff settings
```toml
[tool.ruff]
select = ["TID"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
```

###  The current Ruff version
0.0.270
