### ISSUE TITLE
respect `target-version` in pyupgrade rules

### ISSUE THREAD

**Issue by trim21** [charliermarsh/ruff#4779]
It would be nice if pyupgrade can automaticly disable based on target-version

for example:

```toml
extend-select = ["UP"]
target-version = "py310"
```

then these rules should be disabled automaticly, or become noop

```
UP035 `typing.List` is deprecated, use `list` instead
UP007 [*] Use `X | Y` for type annotations
UP006 [*] Use `list` instead of `List` for type annotation
```
