### ISSUE TITLE
pep8-naming: configuring classmethod-decorators

### ISSUE THREAD

**Issue by olliemath** [charliermarsh/ruff#4832]
# Issue

Currently ruff (0.0.270) does not seem to respect the classmethod-decorators option for pep8-naming. However, in the past this setting was respected. The regression seems to have been introduced in the **0.0.220 -> 0.0.221** release.

# Reproducing  example

With the following snippet (see below for pyproject), ruff 0.0.220 correctly identifies an error only on the "bad" method, whereas current ruff identifies both methods as incorrect:

```python
def extra_classmethod(method):
    return classmethod(method)

class Foo:
    @extra_classmethod
    def good(cls):  # should be ok
        ...

    def bad(cls):  # should be flagged
        ...
```

Here's the pyproject.toml (options taken from docs at https://beta.ruff.rs/docs/settings/#classmethod-decorators):

```toml
[tool.ruff]
select = ['N']
[tool.ruff.pep8-naming]
classmethod-decorators = ['extra_classmethod']
```
