### ISSUE TITLE
Q000 Double/Single quotes message & config

### ISSUE THREAD

**Issue by tgross35** [charliermarsh/ruff#557]
Hello,

Could the readme be updated to show how to configure Q000?

Currently, the readme says the message is "Single quotes found but double quotes preferred". However, the default message seems to be "Double quotes found but single quotes preferred", and I can't figure out how to configure this.

```toml
# pyproject.toml
[tool.ruff]
line-length=88

[tool.ruff.flake8-quotes]
# configured based on example in readme, but the inline option doesn't seem to do anything
docstring-quotes = "double"
inline-quotes = "double"
```

```py
# test.py
ABC = "str"
```

```shell
# CLI
root@5d53afc0df87:/home# ruff --select Q .
Found 1 error(s).
test.py:1:7: Q000 Double quotes found but single quotes preferred
```

Just a little blurb in the readme in the `flake8-quotes` section about how to configure it would be nice. (I'd personally vouch for defaulting to prefer double quotes to match black, even though this doesn't match with the original flake-quotes)
