### ISSUE TITLE
Suppress ANN401 for dynamically typed *args and **kwargs.

### ISSUE THREAD

**Issue by tekumara** [charliermarsh/ruff#677]
Now that ANN401 has [landed](https://github.com/charliermarsh/ruff/pull/657), would be nice to support [allow-star-arg-any](https://github.com/sco1/flake8-annotations#--allow-star-arg-any) which is common idiom, eg:
```python
def mocked_fn(*args: Any, **kwargs: Any) -> None:
   ...
```

**Comment by andersk** [comment]
This is supported.

```toml
[tool.ruff.flake8-annotations]
allow-star-arg-any = true
```
