### ISSUE TITLE
E999 syntax error for match statement

### ISSUE THREAD

**Issue by thosil** [charliermarsh/ruff#680]
ruff throw a syntax error for code like this:
```python3
import sys

value: str = sys.argv[1]

match value:
    case "ruff":
        print("Rough?")
    case "awesome":
        print("Of course is it!")
    case _:
        print("what?")

```

```
$ ruff ruff_and_match.py
Found 1 error(s).
ruff_and_match.py:5:8: E999 SyntaxError: invalid syntax. Got unexpected token 'value'
```

### versions
- Python 3.10.6
- ruff 0.0.108

### config:
```toml
[tool.ruff]
line-length = 100
select=["E", "F", "W", "U", "N", "C", "B", "A", "T", "Q", "
```

(and yes ruff is awesome ;-))
