### ISSUE TITLE
Feature request: sort first-party libraries last

### ISSUE THREAD

**Issue by tekumara** [charliermarsh/ruff#815]
Ruff currently sorts imports without distinction between first-party and third-party libraries.

For feature parity with isort, it would be great if ruff could sort first-party libraries into their own section at the end of the imports. 😍

**Comment by charliermarsh** [comment]
This should be the current behavior! Can you try setting the `src` path in your `pyproject.toml`, like:

```toml
[tool.ruff]
src = [".", "tools", "tools/setup/emoji"]
```
