### ISSUE TITLE
First-party imports not being sorted

### ISSUE THREAD

**Issue by tekumara** [charliermarsh/ruff#844]
_myapp/main.py_:
```python
import myapp.module
import pydantic

print(pydantic.version)
print(myapp.module.hello)
```

_pyproject.toml_
```toml
[tool.ruff]
line-length = 120

# rules to enable/ignore
select = [
    # isort
    "I"
]
# first-party imports for sorting
src = ["myapp"]

fix = true
```

When I run `ruff myapp/main.py` it preserves the sort order above instead of sorting myapp last like isort does, eg:
```python
import pydantic

import myapp.module
```

ruff 0.0.132
