### ISSUE TITLE
Bugbear extend-immutable-calls with import alias does not work

### ISSUE THREAD

**Issue by JonathanPlasse** [charliermarsh/ruff#922]
```python
from fastapi.openapi.models import OAuthFlows as OAuthFlowsModel

def okay_alias(model=OAuthFlowsModel()):
    ...
```

```toml
[tool.ruff]
select = ["B008"]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.openapi.models.OAuthFlows"]
```
